"""低位題材動能選股參數。"""

from __future__ import annotations

MAX_PRICE = 80.0
MAX_MARKET_CAP_BILLION = 300.0
MIN_DIRECTOR_HOLDING_PCT = 25.0
MIN_GAIN_20D_PCT = 12.0
VOLUME_MA_DAYS = 20
VOLUME_BREAKOUT_RATIO = 1.5
HOT_INDUSTRY_TOP_N = 5
HOT_INDUSTRY_COUNT_WEIGHT = 2.0
